# Generated by Django 6.0.2 on 2026-03-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('date_of_trip', models.DateField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.author')),
            ],
        ),
    ]
